### ISSUE TITLE
Unable to build after upgrading to Cordova 7.0.0

### ISSUE THREAD

**Issue by cindyliu-yb** [ionic-team/ionic-plugin-deeplinks#99] opened 2017-05-05 10:31 UTC
Hello, 

I can't do cordova build because of something in the plugin after upgrading to Cordova 7.0.0. See the error below.   Once I remove the plugin, I can build successfully.   

<img width="994" alt="screen shot 2017-05-05 at 11 28 15" src="https://cloud.githubusercontent.com/assets/22146622/25742166/1eb04884-3186-11e7-844b-d8a70d3a827f.png">

Could you fix this? Thanks in advance!

**Comment by ihadeed** [comment] 2017-05-06 01:43
@cindyliu-yb I don't think this is related to this plugin. I was just experiencing the same issue. Run the following command to fix it:
```
sudo npm i -g cordova@6.5.0
```

**Comment by peterpeterparker** [comment] 2017-05-06 12:01
@ihadeed it's related to this plugin

    ionic plugin add ionic-plugin-deeplink
    ionic platform rm ios
    ionic platform add ios

=> Error: Cannot find module '../plugman/platforms/ios'

    ionic plugin rm ionic-plugin-deeplink
    ionic platform rm ios
    ionic platform add ios
    ionic plugin add ionic-plugin-deeplink

=> ok

**Comment by peterpeterparker** [comment] 2017-05-06 12:27
In xcodePreferences.js:

    try {
    // try pre-5.0 cordova structure
    platform_ios = context.requireCordovaModule('cordova-lib/src/plugman/platforms')['ios'];
    projectFile = platform_ios.parseProjectFile(iosPlatformPath());
  } catch (e) {
    // let's try cordova 5.0 structure
    platform_ios = context.requireCordovaModule('cordova-lib/src/plugman/platforms/ios');
    projectFile = platform_ios.parseProjectFile(iosPlatformPath());
  }

But 'cordova-lib/src/plugman/platforms/ios' seems to doesn't exist anymore in Cordova 7.0.0, see following commit:

https://github.com/apache/cordova-lib/commit/64fea70ea0554458ebc399f0ad4ba4b534b5cd3f

**Comment by piotrowski** [comment] 2017-05-06 13:03
So this https://github.com/driftyco/ionic-plugin-deeplinks/blob/master/hooks/afterPrepareHook.js 
is including this https://github.com/driftyco/ionic-plugin-deeplinks/blob/master/hooks/lib/ios/xcodePreferences.js where these lines don't do what they are supposed to do any more: https://github.com/driftyco/ionic-plugin-deeplinks/blob/master/hooks/lib/ios/xcodePreferences.js#L151-L159

**Comment by peterpeterparker** [comment] 2017-05-06 13:25
He you go, a quick and dirty solution. In xcodePreferences.js, replace method loadProjectFile with following code:

    function loadProjectFile() {
      var platform_ios;
      var projectFile;
    
      try {
        // try pre-5.0 cordova structure
        platform_ios = context.requireCordovaModule('cordova-lib/src/plugman/platforms')['ios'];
        projectFile = platform_ios.parseProjectFile(iosPlatformPath());
      } catch (e) {
          try {
              // let's try cordova 5.0 structure
              platform_ios = context.requireCordovaModule('cordova-lib/src/plugman/platforms/ios');
              projectFile = platform_ios.parseProjectFile(iosPlatformPath());
          } catch (e) {
              // Then cordova 7.0
              var project_files = context.requireCordovaModule('glob').sync(path.join(iosPlatformPath(), '*.xcodeproj', 'project.pbxproj'));
    
              if (project_files.length === 0) {
                throw new Error('does not appear to be an xcode project (no xcode project file)');
              }
    
              var pbxPath = project_files[0];
    
              var xcodeproj = context.requireCordovaModule('xcode').project(pbxPath);
              xcodeproj.parseSync();
    
              projectFile = {
                  'xcode': xcodeproj,
                  write: function () {
                      var fs = context.requireCordovaModule('fs');
    
                  var frameworks_file = path.join(iosPlatformPath(), 'frameworks.json');
                  var frameworks = {};
                  try {
                      frameworks = context.requireCordovaModule(frameworks_file);
                  } catch (e) { }

                  fs.writeFileSync(pbxPath, xcodeproj.writeSync());
                      if (Object.keys(frameworks).length === 0){
                          // If there is no framework references remain in the project, just remove this file
                          shell.rm('-rf', frameworks_file);
                          return;
                      }
                      fs.writeFileSync(frameworks_file, JSON.stringify(this.frameworks, null, 4));
                  }
              };
          }
      }
    
      return projectFile;
    }

**Comment by peterpeterparker** [comment] 2017-05-08 18:17
@ihadeed sure, would be my pleasure: https://github.com/driftyco/ionic-plugin-deeplinks/pull/103

**Comment by aramando** [comment] 2017-05-17 15:23
I've come up with a much simpler solution. Can anyone confirm this works as intended? It appears to work OK for me, but I'm insufficiently familiar with the inner machinations of Cordova to know how good a solution it is.

```
function loadProjectFile() {
  var platform_ios;
  var projectFile;
  try {
    // try pre-5.0 cordova structure
    platform_ios = context.requireCordovaModule('cordova-lib/src/plugman/platforms')['ios'];
    projectFile = platform_ios.parseProjectFile(iosPlatformPath());
  } catch (e) {
    try {
      // let's try cordova 5.0 structure
      platform_ios = context.requireCordovaModule('cordova-lib/src/plugman/platforms/ios');
      projectFile = platform_ios.parse(iosPlatformPath());
    } catch (e) {
      // try cordova 7.0 structure
      var iosPlatformApi = require(path.join(iosPlatformPath(), '/cordova/Api'));
      var projectFileApi = require(path.join(iosPlatformPath(), '/cordova/lib/projectFile.js'));
      var locations = (new iosPlatformApi()).locations;
      projectFile = projectFileApi.parse(locations);
    }
  }
  return projectFile;
}
```

**Comment by ihadeed** [comment] 2017-05-17 18:21
@peterpeterparker 's PR was merged, this should be fixed now.

**Comment by peterpeterparker** [comment] 2017-05-17 19:27
@ihadeed yes it's merged and confirm it's fixed but of course Im not against a easier cuter solution, like I said, I did a quick fix

**Comment by mlynch** [comment] 2017-09-19 17:25
btw I removed all the hooks. Caused more problems than they were worth. See #82

**Closed by mlynch** 2017-09-19 17:25 UTC

**Comment by Prodev2017** [comment] 2017-12-16 02:42
I tried to add ionic-plugin-deeplink
but i got errors
 
An error occurred while running cordova plugin add ionic-plugin-deeplink --save (exit 

        code 1):
        
        Error: Registry returned 404 for GET on 
        https://registry.npmjs.org/ionic-plugin-deeplink

Please help me

**Comment by alphapilgrim** [comment] 2018-01-13 22:08
Any update on installation error, I as well am getting a 404. Could really use the help.

**Comment by jeffminsungkim** [comment] 2018-01-25 15:39
Where can I find xcodePreferences.js file?
