### ISSUE TITLE
Opening a link in-app on IOS launches new instance of the app

### ISSUE THREAD

**Issue by vicrep** [ionic-team/ionic-plugin-deeplinks#6] opened 2016-07-05 16:40 UTC
I'm using a messaging framework in my ionic (2) app for in-app chat which gives the option to send users action buttons wrapped as html links, and I've been using this plugin to allow for these buttons to trigger nav changes in the app. This works as expected on Android (tap the link, deep-link observable gets called, and nav-stack gets updated). 

However, on iOS doing the same opens a new instance of the app, with the 'back to <my-app-name>' status-bar button. I've added universal link entitlements to the xCode project, but to no avail. I remember the [Custom-URL-scheme plugin](https://github.com/EddyVerbruggen/Custom-URL-scheme) being able to achieve this kind of functionality with some custom implementation.

Using Cordova-iOS@4.2.0, ionic-plugin-deeplinks@1.0.6, and ionic@2.0.0-beta.10.

**Comment by vicrep** [comment] 2016-07-05 17:16
Ok, so it seems to be a cordova-ios 4.2.0 issue - using 4.1.1 brings this functionality back. Might still be worth taking a look at though.

**Comment by mlynch** [comment] 2016-07-11 16:24
@vicrep glad you got to the bottom of this. Do you have a link to that issue by chance?

**Comment by vicrep** [comment] 2016-07-11 17:23
I've looked and it hasn't actually been logged as an issue, it's just a side effect of updating to 4.2.0. I'll keep on looking to see if I can find the cause of this.

**Comment by mlynch** [comment] 2016-07-11 17:48
Okay, considering that's their current stable release I'm going to dig in and see what might be going on here...

**Comment by vicrep** [comment] 2016-07-11 17:52
So far I've tried setting `allow-navigation`, `allow-intent` on my url scheme, and tinkering with the CSP, to no avail. Note that not having navigation or intent causes a navigation error, and setting either one will cause the aforementioned issue.

**Comment by mlynch** [comment] 2016-08-03 19:45
Okay, I just did some testing here with cordova-ios 4.2.0. I'm not able to reproduce any duplicate app issues. I navigate to my app and it opens. Yes, I see the status bar "back to safari" but that's a hard coded behavior in iOS. Everything appears to be working great, but to verify perhaps upgrade to the new version of the plugin here.

I'm going to close for now, if you think I'm missing something let me know and I'll reopen and try to dig deeper. Thanks.

**Comment by mlynch** [comment] 2016-08-03 19:50
Okay, I thought about this some more. Do you mean you're in your app, and then you tap a link in the app that is a deep link for your same app? For example, a tweet URL inside of Twitter?

And instead of just navigating inside of itself, it's "opening" Twitter again with the status bar updated and such?

**Comment by vicrep** [comment] 2016-08-04 08:18
Yes, the latter is exactly the problem I'm facing, and it occurs only on
Cordova iOS@4.2.0 afaik

**Comment by pwbs** [comment] 2016-09-23 09:35
I'm facing a more or less related problem: with Cordova iOS 4.2.{0,1}, my external links are not opening at all. :(

**Comment by mlynch** [comment] 2017-09-19 17:20
Anyone else notice this outside of Cordova iOS 4.2.0? Haven't gotten any more comments since

**Comment by chrisweight** [comment] 2018-07-13 15:36
Picking this up now - old ticket and no comments, is anyone still using 4.2.0? If not, I'll close this. Speak now, people...

**Closed** 2018-09-26 09:32 UTC
